#!/bin/sh

cd "$(dirname "$0")" || exit 1

# https://stackoverflow.com/a/63286099/1071486
slugify () {
    echo "$1" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr '[:upper:]' '[:lower:]'
}

title="$*"
if [ -z "$title" ]; then
  echo 'Usage: ./draft this is my title'
  exit 1
fi

slug="$(slugify "$title")"
filepath="../_drafts/$slug.md"
cat >"$filepath" <<EOF
---
title: $title
tags: []
---


EOF

"$EDITOR" "$filepath"
