#!/usr/bin/env node

const fs = require('fs');
const matter = require('gray-matter');
const path = require('path');
const datefns = require('date-fns');
const prettier = require('prettier');

const filepath = process.argv[2];
const filecontent = fs.readFileSync(filepath);
const { content, data } = matter(filecontent);
const canonicalURL = `https://aymericbeaumet.com/${path.basename(
	path.basename(filepath, path.extname(filepath)),
)}`;

if (data.tags.length > 4) {
	throw new Error('dev.to supports at most 4 tags');
}

const newcontent = `
---

_For a better reading experience, read the article where it was originally posted: ${canonicalURL}_

---

${prettier.format(content, {
	parser: 'markdown',
	proseWrap: 'never',
})}`.replace(/]\(([./#?][^)]*)\)/, `](${canonicalURL}$1)`); // replacing relative links

const newdata = {
	published: true,
	title: data.title,
	date: datefns.format(data.date, "yyyy-MM-dd '00:00:00 UTC'"),
	tags: data.tags,
	canonical_url: canonicalURL,
	// cover_image:
	// description:
	// series:
};

process.stdout.write(matter.stringify(newcontent, newdata).trimEnd());
