#!/usr/bin/env node

const fs = require('fs');
const slugify = require('slugify');
const format = require('date-fns/format');
const path = require('path');

const title = process.argv[2];
const slug = slugify(title, { lower: true, strict: true });
const date = format(new Date(), 'yyyy-MM-dd');
const filepath = path.join(__dirname, '../data/posts', slug, 'index.md');

try {
	fs.mkdirSync(path.dirname(filepath), 0o755);
	fs.writeFileSync(
		filepath,
		`---
title: ${JSON.stringify(title)}
tags: []
date: ${date}
thumbnail: ./thumbnail.jpg
---

`,
	);
} catch (_) {
	// noop
}

console.log(`$EDITOR ${JSON.stringify(filepath)}`); // TODO: execve
