#!/usr/bin/env node

const fs = require('fs');
const slugify = require('slugify');
const format = require('date-fns/format');
const path = require('path');

const title = process.argv[2];
const slug = slugify(title, { lower: true, strict: true });
const date = format(new Date(), 'yyyy-MM-dd');
const filepath = path.join(__dirname, `../_posts`, `${slug}.md`);

fs.writeFileSync(
	filepath,
	`---
title: ${JSON.stringify(title)}
tags: []
date: ${date}
---

`,
);

console.log(`$EDITOR ${JSON.stringify(filepath)}`); // TODO: execve
